---
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "docker.io/mesames/idm-comfyui-custom:usegoogle"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "login"
      - "-u"
      - "$_DOCKER_HUB_USERNAME"
      - "-p"
      - "$_DOCKER_HUB_TOKEN"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "docker.io/mesames/idm-comfyui-custom:usegoogle"
